define ->
  stateList =    
    US: [
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['American Samoa', 'AS'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['District Of Columbia', 'DC'],
      ['Federated States Of Micronesia', 'FM'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Guam Gu', 'GU'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Marshall Islands', 'MH'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Northern Mariana Islands', 'MP'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Palau', 'PW'],
      ['Pennsylvania', 'PA'],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virgin Islands', 'VI'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
    ]
    Canada: [
      ['Alberta', 'AB'],
      ['British Columbia', 'BC'],
      ['Manitoba', 'MB'],
      ['New Brunswick', 'NB'],
      ['Newfoundland & Labr.', 'NL'],
      ['Nova Scotia', 'NS'],
      ['NW Territories', 'NT'],
      ['Nunavut', 'NU'],
      ['Ontario', 'ON'],
      ['Prince Edward Island', 'PE'],
      ['Quebec', 'QC'],
      ['Saskatchewan', 'SK']
    ]
    India: [
      ['Andhra Pradesh', 'AP'],
      ['Arunachal Pradesh', 'AR'],
      ['Assam', 'AS'],
      ['Bihar', 'BR'],
      ['Chhattisgarh', 'CT'],
      ['Goa', 'GA'],
      ['Gujarat', 'GJ'],
      ['Haryana', 'HR'],
      ['Himachal Pradesh', 'HP'],
      ['Jammu & Kashmir', 'JK'],
      ['Jharkhand', 'JH'],
      ['Karnataka', 'KA'],
      ['Kerala', 'KL'],
      ['Madhya Pradesh', 'MP'],
      ['Maharashtra', 'MH'],
      ['Manipur', 'MN'],
      ['Meghalaya', 'ML'],
      ['Mizoram', 'MZ'],
      ['Nagaland', 'NL'],
      ['Odisha', 'OR'],
      ['Punjab', 'PB'],
      ['Rajasthan', 'RJ'],
      ['Sikkim', 'SK'],
      ['Tamil Nadu', 'TN'],
      ['Tripura', 'TR'],
      ['Uttarakhand', 'UK'],
      ['Uttar Pradesh', 'UP'],
      ['West Bengal', 'WB'],
      ['Andaman & Nicobar', 'AN'],
      ['Chandigarh', 'CH'],
      ['Dadra and Nagar Haveli', 'DN'],
      ['Daman & Diu', 'DD'],
      ['Delhi', 'DL'],
      ['Lakshadweep', 'LD'],
      ['Puducherry', 'PY']
    ]